version: '3.8'
services:
  movies:
    image: shubhamdevops096/paytmmoviesrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  recharge:
    image: shubhamdevops096/paytmrechargerepo:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
